time:2022-07-19 15:01:51,msg:float() argument must be a string or a number, not 'NoneType'
time:2022-07-19 15:01:51,msg:None
time:2022-07-19 15:01:51,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1063, in stepOrder
    self.addOrder(optype = 'buy', code = pointCode.get('code'), price = pointCode.get('price'), timedate = pointCode.get('timedate'))
  File "/var/yp/source/bigdata/src/Shipan.py", line 1619, in addOrder
    db_mysql.insertOrders(type=optype, currency=order.get('currency'), price=float(order.get('price')), timedate=func.transTimedateToDate(timedate), code=code, complete=0, suc=0, profit=0)
TypeError: float() argument must be a string or a number, not 'NoneType'

time:2022-07-19 19:55:10,msg:(400, -2011, 'Unknown order sent.', {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '42', 'Connection': 'keep-alive', 'Date': 'Tue, 19 Jul 2022 11:55:10 GMT', 'Server': 'nginx', 'X-SAPI-USED-IP-WEIGHT-1M': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 00f66bc6263192200d1a0cdb83e969f8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS1-P1', 'X-Amz-Cf-Id': '3HCB134mtSaonYp3uewgUXEKfvfqJFz-E5I9xIvlCsnhtepPGApNSA=='})
time:2022-07-19 19:55:10,msg:None
time:2022-07-19 19:55:10,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1099, in stepOrder
    optres = self.trade.sell(usdT = self.initUsdtUint, price = pointCode.get('price'), tradeVariety = self.tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 71, in sell
    return self.trade_binance('SELL', usdT, price, trytime, tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 321, in trade_binance
    self.gate_trade.margin_open_orders_cancellation(cpair)
  File "/usr/local/lib/python3.9/dist-packages/binance/spot/margin.py", line 393, in margin_open_orders_cancellation
    return self.sign_request("DELETE", "/sapi/v1/margin/openOrders", payload)
  File "/usr/local/lib/python3.9/dist-packages/binance/api.py", line 83, in sign_request
    return self.send_request(http_method, url_path, payload)
  File "/usr/local/lib/python3.9/dist-packages/binance/api.py", line 117, in send_request
    self._handle_exception(response)
  File "/usr/local/lib/python3.9/dist-packages/binance/api.py", line 170, in _handle_exception
    raise ClientError(status_code, err["code"], err["msg"], response.headers)
binance.error.ClientError: (400, -2011, 'Unknown order sent.', {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '42', 'Connection': 'keep-alive', 'Date': 'Tue, 19 Jul 2022 11:55:10 GMT', 'Server': 'nginx', 'X-SAPI-USED-IP-WEIGHT-1M': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 00f66bc6263192200d1a0cdb83e969f8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS1-P1', 'X-Amz-Cf-Id': '3HCB134mtSaonYp3uewgUXEKfvfqJFz-E5I9xIvlCsnhtepPGApNSA=='})

time:2022-07-19 21:33:30,msg:name 'client' is not defined
time:2022-07-19 21:33:30,msg:None
time:2022-07-19 21:33:30,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1099, in stepOrder
    optres = self.trade.sell(usdT = self.initUsdtUint, price = pointCode.get('price'), tradeVariety = self.tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 71, in sell
    return self.trade_binance('SELL', usdT, price, trytime, tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 326, in trade_binance
    return self.sell(usdT, price, trytime - 1, tradeVariety = tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 71, in sell
    return self.trade_binance('SELL', usdT, price, trytime, tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 329, in trade_binance
    show_order = client.margin_order(symbol = cpair, orderId = new_order['orderId'])
NameError: name 'client' is not defined

time:2022-07-19 21:47:51,msg:name 'client' is not defined
time:2022-07-19 21:47:51,msg:None
time:2022-07-19 21:47:51,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1048, in stepOrder
    optres = self.trade.buy(usdT = spendUsdt, price = pointCode.get('price'), tradeVariety = self.tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 84, in buy
    return self.trade_binance('BUY', usdT, price, trytime, tradeVariety)
  File "/var/yp/source/bigdata/src/Trade.py", line 329, in trade_binance
    show_order = client.margin_order(symbol = cpair, orderId = new_order['orderId'])
NameError: name 'client' is not defined

time:2022-07-20 12:16:07,msg:name 'p' is not defined
time:2022-07-20 12:16:07,msg:None
time:2022-07-20 12:16:08,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1002, in stepOrder
    pc = self.getPoint(timeLeft, timeRight)
  File "/var/yp/source/bigdata/src/Shipan.py", line 825, in getPoint
    return self.paint.getPoint(timeStart, timeEnd)
  File "/var/yp/source/bigdata/src/Paint.py", line 849, in getPoint
    p.printRunTime('point start 1')
NameError: name 'p' is not defined

time:2022-07-20 12:16:11,msg:name 'p' is not defined
time:2022-07-20 12:16:11,msg:None
time:2022-07-20 12:16:11,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1002, in stepOrder
    pc = self.getPoint(timeLeft, timeRight)
  File "/var/yp/source/bigdata/src/Shipan.py", line 825, in getPoint
    return self.paint.getPoint(timeStart, timeEnd)
  File "/var/yp/source/bigdata/src/Paint.py", line 849, in getPoint
    p.printRunTime('point start 1')
NameError: name 'p' is not defined

time:2022-07-23 22:57:20,msg:dumpTrade() missing 2 required positional arguments: 'timedate' and 'price'
time:2022-07-23 22:57:20,msg:None
time:2022-07-23 22:57:20,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1163, in stepOrder
    self.dumpTrade()
TypeError: dumpTrade() missing 2 required positional arguments: 'timedate' and 'price'

time:2022-07-26 19:17:29,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:17:29,msg:None
time:2022-07-26 19:17:29,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(lo.get('timedate'), lo.get('price'))
  File "/var/yp/source/bigdata/src/Shipan.py", line 1323, in dumpTrade
    result_obj = self.getTradeResult(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1235, in getTradeResult
    self.pingc(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1341, in pingc
    self.orders[i]['ptimedate'] = func.transTimedateToDate(timedate)
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:17:32,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:17:32,msg:None
time:2022-07-26 19:17:32,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(lo.get('timedate'), lo.get('price'))
  File "/var/yp/source/bigdata/src/Shipan.py", line 1323, in dumpTrade
    result_obj = self.getTradeResult(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1235, in getTradeResult
    self.pingc(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1341, in pingc
    self.orders[i]['ptimedate'] = func.transTimedateToDate(timedate)
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:17:36,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:17:36,msg:None
time:2022-07-26 19:17:36,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(lo.get('timedate'), lo.get('price'))
  File "/var/yp/source/bigdata/src/Shipan.py", line 1323, in dumpTrade
    result_obj = self.getTradeResult(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1235, in getTradeResult
    self.pingc(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1341, in pingc
    self.orders[i]['ptimedate'] = func.transTimedateToDate(timedate)
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:31,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:31,msg:None
time:2022-07-26 19:18:31,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:35,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:35,msg:None
time:2022-07-26 19:18:35,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:38,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:38,msg:None
time:2022-07-26 19:18:38,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:42,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:42,msg:None
time:2022-07-26 19:18:42,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:46,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:46,msg:None
time:2022-07-26 19:18:46,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:49,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:49,msg:None
time:2022-07-26 19:18:49,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:53,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:53,msg:None
time:2022-07-26 19:18:53,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:18:56,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:18:56,msg:None
time:2022-07-26 19:18:56,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:00,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:00,msg:None
time:2022-07-26 19:19:00,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:04,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:04,msg:None
time:2022-07-26 19:19:04,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:07,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:07,msg:None
time:2022-07-26 19:19:07,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:11,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:11,msg:None
time:2022-07-26 19:19:11,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:14,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:14,msg:None
time:2022-07-26 19:19:14,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:18,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:18,msg:None
time:2022-07-26 19:19:18,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:22,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:22,msg:None
time:2022-07-26 19:19:22,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:25,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:25,msg:None
time:2022-07-26 19:19:25,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:29,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:29,msg:None
time:2022-07-26 19:19:29,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:32,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:32,msg:None
time:2022-07-26 19:19:32,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transTimedateToDate(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-26 19:19:36,msg:time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'
time:2022-07-26 19:19:36,msg:None
time:2022-07-26 19:19:36,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 986, in stepOrder
    self.dumpTrade(func.transF1ToTimedateF2(lo.get('timedate')), lo.get('price'))
  File "/var/yp/source/bigdata/src/func.py", line 31, in transTimedateToDate
    tm_s = transTimedateToTime(timedate) + 8 * 3600
  File "/var/yp/source/bigdata/src/func.py", line 20, in transTimedateToTime
    timedate_stuct = time.strptime(str(timedate), f2)
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-07-26 08:30:55' does not match format '%Y%m%d%H%M%S'

time:2022-07-27 23:47:34,msg:local variable 'c_profit' referenced before assignment
time:2022-07-27 23:47:34,msg:None
time:2022-07-27 23:47:34,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 1217, in stepOrder
    self.dumpTrade(pointCode.get('timedate'), pointCode.get('price'))
  File "/var/yp/source/bigdata/src/Shipan.py", line 1371, in dumpTrade
    result_obj = self.getTradeResult(timedate, price)
  File "/var/yp/source/bigdata/src/Shipan.py", line 1368, in getTradeResult
    return {"result_str": result_str, "opt": opt, "amount": amount, "open_price": open_price, "profit": "%.2f" % c_profit}
UnboundLocalError: local variable 'c_profit' referenced before assignment

time:2022-07-28 00:46:56,msg:cannot convert float NaN to integer
time:2022-07-28 00:46:56,msg:None
time:2022-07-28 00:46:56,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 967, in stepOrder
    pc = self.getPoint(timeLeft, timeRight)
  File "/var/yp/source/bigdata/src/Shipan.py", line 790, in getPoint
    return self.paint.getPoint(timeStart, timeEnd)
  File "/var/yp/source/bigdata/src/Paint.py", line 949, in getPoint
    nd_obj = self.drawBaseIndexCode(dataCodeArea, dataCodeArea, ah = 22, aw = 40, kh = 22, kw = 80)
  File "/var/yp/source/bigdata/src/Paint.py", line 197, in drawBaseIndexCode
    amountBuyTotal = self.getIndexNum(dataBase, buydata, height, width)
  File "/var/yp/source/bigdata/src/Paint.py", line 431, in getIndexNum
    nd_key = int((price - minprice) / subPerHeight)
ValueError: cannot convert float NaN to integer

time:2022-07-28 00:46:59,msg:cannot convert float NaN to integer
time:2022-07-28 00:46:59,msg:None
time:2022-07-28 00:46:59,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 967, in stepOrder
    pc = self.getPoint(timeLeft, timeRight)
  File "/var/yp/source/bigdata/src/Shipan.py", line 790, in getPoint
    return self.paint.getPoint(timeStart, timeEnd)
  File "/var/yp/source/bigdata/src/Paint.py", line 949, in getPoint
    nd_obj = self.drawBaseIndexCode(dataCodeArea, dataCodeArea, ah = 22, aw = 40, kh = 22, kw = 80)
  File "/var/yp/source/bigdata/src/Paint.py", line 197, in drawBaseIndexCode
    amountBuyTotal = self.getIndexNum(dataBase, buydata, height, width)
  File "/var/yp/source/bigdata/src/Paint.py", line 431, in getIndexNum
    nd_key = int((price - minprice) / subPerHeight)
ValueError: cannot convert float NaN to integer

time:2022-07-28 08:31:37,msg:index -1 is out of bounds for axis 0 with size 0
time:2022-07-28 08:31:37,msg:None
time:2022-07-28 08:31:37,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 743, in stepOrder
    self.updateNewData()
  File "/var/yp/source/bigdata/src/Shipan.py", line 695, in updateNewData
    tdata = self.cha.getLastTimeAreaData()
  File "/var/yp/source/bigdata/src/Characteristic.py", line 29, in getLastTimeAreaData
    return data.loc[data.index[-1]]
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 5039, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0

time:2022-07-28 08:31:40,msg:index -1 is out of bounds for axis 0 with size 0
time:2022-07-28 08:31:40,msg:None
time:2022-07-28 08:31:40,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 743, in stepOrder
    self.updateNewData()
  File "/var/yp/source/bigdata/src/Shipan.py", line 695, in updateNewData
    tdata = self.cha.getLastTimeAreaData()
  File "/var/yp/source/bigdata/src/Characteristic.py", line 29, in getLastTimeAreaData
    return data.loc[data.index[-1]]
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 5039, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0

time:2022-07-28 08:31:43,msg:index -1 is out of bounds for axis 0 with size 0
time:2022-07-28 08:31:43,msg:None
time:2022-07-28 08:31:43,msg:traceback.format_exc():
Traceback (most recent call last):
  File "/var/yp/source/bigdata/src/Shipan.py", line 743, in stepOrder
    self.updateNewData()
  File "/var/yp/source/bigdata/src/Shipan.py", line 695, in updateNewData
    tdata = self.cha.getLastTimeAreaData()
  File "/var/yp/source/bigdata/src/Characteristic.py", line 29, in getLastTimeAreaData
    return data.loc[data.index[-1]]
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 5039, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0

